name: "Exercicio 2 - Ivan"

on: push
  
jobs:
  cria_e_upload_artefato:
    name: "Cria artefato e faz upload"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
